### ISSUE TITLE
php artisan migrate Failure

### ISSUE THREAD

**Issue by vortex1409** [supertassu/statu#1]
Command: php artisan migrate

Output

Migrating: 2019_01_06_084407_create_incidents_table

`Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `resolved` tinyint(1) not null default '0', `created_at` timestamp nu' at line 1 (SQL: create table `incidents` (`id` int unsigned not null auto_increment primary key, `title` varchar(255) not null, `description` text null, `affected_components` json null, `resolved` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

**Comment by supertassu** [comment]
Hey @vortex1409!

I'm unable to reproduce this issue on my local machine, what version of MySQL server are you using?

Also, what PHP version are you using?

tassu

**Comment by vortex1409** [comment]
Hey @supertassu 

PHP 7.2
MySQL 5.5.57-0ubuntu0.14.04.1

My Dev environment is in AWS Cloud9

**Comment by supertassu** [comment]
I've pushed 004bd0294eb1624a73271148b4904d3887be14c4. Does that fix the issue?

**Comment by vortex1409** [comment]
@supertassu Apparently not. This is weird.

`
2019_01_06_084407_create_incidents_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `resolved` tinyint(1) not null default '0', `created_at` timestamp nu' at line 1 (SQL: create table `incidents` (`id` int unsigned not null auto_increment primary key, `title` varchar(255) not null, `description` text null, `affected_components` json null, `resolved` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `resolved` tinyint(1) not null default '0', `created_at` timestamp nu' at line 1")
      /home/ubuntu/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `resolved` tinyint(1) not null default '0', `created_at` timestamp nu' at line 1")
      /home/ubuntu/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61

  Please use the argument -v to see more details.
`

**Comment by supertassu** [comment]
Weird. I'll take a closer look later today.

**Comment by supertassu** [comment]
I've done some testing and this seems like some weird issue with MySQL 5.5 and 5.6. Are you able to try with MySQL 5.7 (or newer)?

**Comment by vortex1409** [comment]
@supertassu I will update when I get a chance to upgrade the MySQL server.

**Comment by vortex1409** [comment]
@supertassu MySQL 5.7 resolved the migration issue.
